-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 15:43:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_educaTI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_educaTI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_educaTI` DEFAULT CHARACTER SET utf8 ;
USE `db_educaTI` ;

-- -----------------------------------------------------
-- Table `db_educaTI`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_educaTI`.`tb_usuario` (
  `nome_usuario` VARCHAR(255) NOT NULL,
  `email_usuario` VARCHAR(255) NOT NULL,
  `senha_usuario` VARCHAR(255) NOT NULL,
  `cpf_usuario` VARCHAR(11) NOT NULL,
  UNIQUE INDEX `senha_usuario_UNIQUE` (`senha_usuario` ASC) VISIBLE,
  UNIQUE INDEX `cpf_usuario_UNIQUE` (`cpf_usuario` ASC) VISIBLE,
  PRIMARY KEY (`email_usuario`),
  UNIQUE INDEX `email_usuario_UNIQUE` (`email_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_educaTI`.`tb_temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_educaTI`.`tb_temas` (
  `id_temas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_temas` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_temas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_educaTI`.`tb_inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_educaTI`.`tb_inscricao` (
  `tb_usuario_nome_usuario` VARCHAR(255) NOT NULL,
  `tb_temas_id_temas` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`tb_usuario_nome_usuario`, `tb_temas_id_temas`),
  INDEX `fk_tb_usuario_has_tb_temas_tb_temas1_idx` (`tb_temas_id_temas` ASC) VISIBLE,
  INDEX `fk_tb_usuario_has_tb_temas_tb_usuario_idx` (`tb_usuario_nome_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_has_tb_temas_tb_usuario`
    FOREIGN KEY (`tb_usuario_nome_usuario`)
    REFERENCES `db_educaTI`.`tb_usuario` (`nome_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_has_tb_temas_tb_temas1`
    FOREIGN KEY (`tb_temas_id_temas`)
    REFERENCES `db_educaTI`.`tb_temas` (`id_temas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_educaTI`.`tb_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_educaTI`.`tb_posts` (
  `id_posts` INT NOT NULL,
  `texto_posts` VARCHAR(1000) NOT NULL,
  `titulo_posts` VARCHAR(45) NOT NULL,
  `multim_posts` VARCHAR(1000) NULL DEFAULT 'Sem imagens',
  `data_posts` TIMESTAMP(45) NOT NULL,
  `tb_usuario_nome_usuario` VARCHAR(255) NOT NULL,
  `tb_temas_id_temas` INT UNSIGNED NOT NULL,
  `nivel_tema` ENUM('C1','C2','C3') NOT NULL,
  PRIMARY KEY (`id_posts`),
  INDEX `fk_tb_posts_tb_usuario1_idx` (`tb_usuario_nome_usuario` ASC) VISIBLE,
  INDEX `fk_tb_posts_tb_temas1_idx` (`tb_temas_id_temas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_posts_tb_usuario1`
    FOREIGN KEY (`tb_usuario_nome_usuario`)
    REFERENCES `db_educaTI`.`tb_usuario` (`nome_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_posts_tb_temas1`
    FOREIGN KEY (`tb_temas_id_temas`)
    REFERENCES `db_educaTI`.`tb_temas` (`id_temas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
